storage:
  files:
    currentDate: test_current.log
    history: test_history.log
logging.level.com.jad: DEBUG
sensors:
  history:
    lsf:
      minLos: 2
    interval.seconds: 60
  read:
    interval.seconds: 2